# Generated by Django 3.1.4 on 2021-01-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                ("name", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=50)),
                ("salt", models.CharField(max_length=50)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(default="offline", max_length=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_recorded", models.DateTimeField()),
                ("device_state", models.JSONField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        related_query_name="telemetry",
                        to="device.device",
                    ),
                ),
            ],
        ),
    ]
