version: "3.8"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: ./web
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - .web.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env.dev
  mqtt_bridge:
    build: ./mqtt_bridge
    env_file:
      - .mqtt_bridge.env.dev
    depends_on:
      - mqtt
  mqtt:
    image: eclipse-mosquitto:2.0.5
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
  static_volume:
  postgres_data: